image: toshiclick/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

cache:
  # ブランチ毎にキャッシュする設定
  key: "$CI_COMMIT_REF_NAME"
#  untracked: true
  paths:
    - .gradle/
    - android-sdk-linux/

before_script:
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -o -q -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

stages:
  - build
  - test_and_lint

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug

assembleRelease:
  stage: build
  script:
    - openssl aes-256-cbc -k $KEYSTORE_DECRYPT_PASSWORD -d -in encrypted-release.jks -out release.jks
#    - openssl aes-256-cbc -k $JSON_DECRYPT_PASSWORD -d -in encrypted-google-services.json -out app/google-services.json -md md5
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release

debugTests:
  stage: test_and_lint
  script:
    - ./gradlew -Pci --console=plain :app:testDebug

lintDebug:
  stage: test_and_lint
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

.android_deploygate:
  stage: deploy
  script:
    - cd android/app/build/outputs/apk/release
    - curl -f -F "file=@app-release.apk" -F "token=${DEPLOY_GATE_TOKEN}" -F "distribution_name=develop" -F "release_note=${CI_PIPELINE_ID} is build" -F "message=${CI_PIPELINE_ID} is build" https://deploygate.com/api/users/toshi-click/apps
    - if [ $? != 0 ]; then exit 1 ;fi
    # ユーザの自動追加 既に追加されているユーザはエラーになるので、エラーコードの確認などはしない
#    - curl -F "users=toshiyuki1986" -F "role=1" -F "token=${DEPLOY_GATE_TOKEN}"
  dependencies:
    - build
  only:
    refs:
      - master
    variables:
      # 変数があるときだけ実施
      - $ANDROID_RELEASE

# playStoreへ自動リリース
.android_release_playstore:
  stage: deploy
  variables:
    LANG: C.UTF-8
  script:
    - openssl aes-256-cbc -k $PUBLISHER_KEYS_JSON_DECRYPT_PASSWORD -d -in encrypted-publisher-keys.json -out app/publisher-keys.json -md md5
    - bundle install
    - bundle exec fastlane android deploy
  dependencies:
    - build
  only:
    refs:
      - master
    variables:
      # 変数があるときだけ実施
      - $ANDROID_RELEASE
