# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Develop Build"
  lane :developBuild do
    gradle(
      task: "assembleDebug",
    )
  end

  desc "Submit a new Release Build"
  lane :releaseBuild do
    gradle(
      task: "assembleRelease",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      apk: './app/build/outputs/apk/release/app-release.apk',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  after_all do |lane|
    slack(
      channel: "#general",
      message: ":clap: Successfully deployed new App Update.＼(^o^)／"
    )
  end

  error do |lane, exception|
    slack(
      channel: "#general",
      message: exception.message,
      success: false
    )
  end
end
